title: Page de référentiel
logo: /assets/img/logo.png
description: Standardisez vos référentiels
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/utilities-repository-page"
url: "https://lesagnic.github.io"
